# Generated by Django 3.2.18 on 2023-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20230507_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='address',
        ),
    ]
