# Generated by Django 3.2.18 on 2023-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('checkoutId', models.IntegerField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='shipment',
        ),
    ]
