# Generated by Django 3.2.18 on 2023-05-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0002_rename_user_registration_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='type',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
