# Generated by Django 3.2.18 on 2023-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('productId', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
