# Generated by Django 3.2.18 on 2023-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
