# Generated by Django 3.2.18 on 2023-05-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutmodel_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutmodel',
            old_name='isActive',
            new_name='isPay',
        ),
    ]
