# Generated by Django 3.2.18 on 2023-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartmodel_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
