# Generated by Django 3.2.18 on 2023-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
