# Generated by Django 3.2.18 on 2023-05-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0003_auto_20230507_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoese',
            new_name='Shoes',
        ),
    ]
